### ISSUE TITLE
unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by zhangfan112** [GrowthEase/GameSentry#1]
Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
(node:62528) UnhandledPromiseRejectionWarning: Error: Device not found
    at getMatchingDevice (D:\PythonProjects\GameSentry\node_modules\frida\dist\index.js:109:15)
    at async D:\PythonProjects\GameSentry\index.js:162:20
(Use `node --trace-warnings ...` to show where the warning was created)
(node:62528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by GrowthEase** [comment]
麻烦检查一下frida环境是否正常，详细使用文档（doc/InstructionsForUse.md）
