### ISSUE TITLE
咋个使用 ，点击启动 就没有后续了

### ISSUE THREAD

**Issue by iyzwei4666** [GrowthEase/GameSentry#3]
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/19775371/206886686-1bf517ad-81e0-4776-a73f-3bbee959f02e.png">

**Comment by GrowthEase** [comment]
有几种方法可以排查异常：
1.console中会有相关的日志
2.检查apk是否已经被加固
3.检查apk是否是游戏，且为工具支持的游戏引擎（文档在doc/InstructionsForUse.md）
