### ISSUE TITLE
unluac failed 

### ISSUE THREAD

**Issue by Chensem** [GrowthEase/GameSentry#7]
Hey , when i use your tool to dump some xlua lua scripts  , and use unluac.jar to decompile luac scripts , i encounter some problems , some scripts can be decompile success , but some scripts decompile failed , the error msg like below .
![image](https://user-images.githubusercontent.com/27469499/212006379-e67cfa0f-eb26-463f-a54c-4ca89bcadc4e.png)
but decompile other scripts , some of them maybe success , so the opcode isn't be changed .
![image](https://user-images.githubusercontent.com/27469499/212006567-30e90eaf-6ac4-43bf-aee7-ec8787639450.png)
if you need to sample to reproduction , please contact me .

**Comment by GrowthEase** [comment]
hi,GameSentry is only to dump lua from memory。If decompiling lua file using unluac fails, you can use 010editor to check the file is a standard lua file. unluac does not support decompilation of non-standard files。
